# Generated by Django 5.0 on 2024-01-14 06:25

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicianModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100, unique=True)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('PhoneNumber', phonenumber_field.modelfields.PhoneNumberField(default='+880', max_length=128, region=None)),
                ('IntrumentType', models.CharField(choices=[('Guitar', 'Guitar'), ('Tabla', 'Tabla'), ('Harmony', 'Harmony'), ('Behala', 'Behala'), ('Ektara', 'Ektara')], max_length=100)),
            ],
        ),
    ]
