# Generated by Django 5.0 on 2024-01-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='car/media/images/'),
        ),
    ]
