# Generated by Django 5.0 on 2024-01-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_carmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsmodel',
            name='Email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
