# Generated by Django 5.0 on 2024-01-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_carmodel_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='customer',
        ),
    ]
